# Generated by Django 2.0.7 on 2019-02-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190201_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcompany',
            name='tag',
            field=models.CharField(default='Seeker', max_length=10),
        ),
        migrations.AddField(
            model_name='pmodel',
            name='tag',
            field=models.CharField(default='Model', max_length=10),
        ),
    ]
