# Generated by Django 2.0.7 on 2019-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190203_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmodel',
            name='model_image',
            field=models.ImageField(default='Users/Model/user.png', upload_to='Users/Model'),
        ),
    ]
