# Generated by Django 2.0.7 on 2019-02-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20190204_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to="'Users'+User")),
                ('User', models.ForeignKey(on_delete='CASCADE', to='account.Pmodel')),
            ],
        ),
    ]
