# Generated by Django 2.0.7 on 2019-02-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190211_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='User',
            new_name='Users',
        ),
    ]
