# Generated by Django 2.0.7 on 2019-02-20 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190211_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmodel',
            old_name='eye_color',
            new_name='skin_color',
        ),
    ]
