# Generated by Django 2.0.7 on 2019-02-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20190220_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmodel',
            name='height',
            field=models.PositiveIntegerField(),
        ),
    ]
