# Generated by Django 2.0.7 on 2019-02-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190220_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmodel',
            name='height',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
