# Generated by Django 2.0.7 on 2019-02-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20190221_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmodel',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
