# Generated by Django 2.0.7 on 2019-04-07 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.STAR_RATINGS_RATING_MODEL),
        ('account', '0013_auto_20190404_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmodel',
            name='model_rating',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.STAR_RATINGS_RATING_MODEL),
        ),
    ]
