# Generated by Django 2.0.7 on 2019-04-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_pmodel_model_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmodel',
            name='model_rating',
        ),
    ]
