# Generated by Django 2.0.7 on 2019-04-07 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_pmodel_model_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmodel',
            name='model_rating',
            field=models.IntegerField(default=1),
        ),
    ]
