# Generated by Django 2.0.7 on 2019-04-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_pmodel_model_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmodel',
            name='model_rating',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
