# Generated by Django 2.0.7 on 2019-04-07 03:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20190407_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmodel',
            name='model_rating',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.STAR_RATINGS_RATING_MODEL),
        ),
    ]
