# Generated by Django 2.0.7 on 2019-04-07 02:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('account', '0020_auto_20190407_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmodel',
            name='average',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='pmodel',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='pmodel',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pmodel',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pmodel',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='pmodel',
            name='model_rating',
        ),
        migrations.AlterUniqueTogether(
            name='pmodel',
            unique_together={('content_type', 'object_id')},
        ),
    ]
