# Generated by Django 2.0.7 on 2019-04-15 03:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.STAR_RATINGS_RATING_MODEL),
        ('account', '0021_auto_20190407_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmodel',
            name='model_rating',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.STAR_RATINGS_RATING_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='pmodel',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pmodel',
            name='average',
        ),
        migrations.RemoveField(
            model_name='pmodel',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='pmodel',
            name='count',
        ),
        migrations.RemoveField(
            model_name='pmodel',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='pmodel',
            name='total',
        ),
    ]
