# Generated by Django 2.0.7 on 2019-04-15 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20190415_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmodel',
            name='model_rating',
        ),
    ]
