# Generated by Django 2.0.7 on 2019-01-29 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('tags', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=100)),
                ('height', models.PositiveIntegerField(blank=True)),
                ('personal_note', models.TextField()),
                ('jslug', models.SlugField()),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.Gender')),
            ],
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Jobs.States'),
        ),
        migrations.AddField(
            model_name='job',
            name='lga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.Lga'),
        ),
        migrations.AddField(
            model_name='job',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.States'),
        ),
    ]
