# Generated by Django 2.0.7 on 2019-01-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0002_auto_20190129_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Featured_Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs', models.ManyToManyField(to='Jobs.Job')),
            ],
        ),
        migrations.CreateModel(
            name='Hot_Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobs', models.ManyToManyField(to='Jobs.Job')),
            ],
        ),
    ]
