# Generated by Django 2.0.7 on 2019-01-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0003_featured_jobs_hot_jobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='gender',
        ),
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.ManyToManyField(to='Jobs.Gender'),
        ),
    ]
