# Generated by Django 2.0.7 on 2019-01-30 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0007_auto_20190130_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='author',
            new_name='Job_author',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='title',
            new_name='Job_title',
        ),
    ]
