# Generated by Django 2.0.7 on 2019-01-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0008_auto_20190130_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='personal_note',
            field=models.TextField(blank=True),
        ),
    ]
