# Generated by Django 2.0.7 on 2019-01-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0010_auto_20190131_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='personal_note',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
