# Generated by Django 2.0.7 on 2019-02-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0011_auto_20190131_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(blank=True, max_length=50)),
                ('Job_author', models.CharField(blank=True, max_length=50)),
                ('applicant', models.CharField(blank=True, max_length=100)),
                ('applicant_id', models.PositiveIntegerField()),
                ('author_id', models.PositiveIntegerField()),
            ],
        ),
    ]
