# Generated by Django 2.0.7 on 2019-02-12 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0012_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='author_id',
        ),
    ]
