# Generated by Django 2.0.7 on 2019-02-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0013_remove_application_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='author_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
