# Generated by Django 2.0.7 on 2019-02-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0014_application_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
