# Generated by Django 2.0.7 on 2019-02-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0015_application_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='lga',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
