# Generated by Django 2.0.7 on 2019-02-18 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0016_auto_20190218_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lga',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Jobs.States'),
        ),
    ]
