# Generated by Django 2.0.7 on 2019-02-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0017_auto_20190218_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lga',
            name='state',
        ),
        migrations.RemoveField(
            model_name='job',
            name='lga',
        ),
        migrations.DeleteModel(
            name='Lga',
        ),
    ]
