# Generated by Django 2.0.7 on 2019-02-18 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0018_auto_20190218_0759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lga', models.CharField(max_length=50, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Jobs.States')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='lga',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.Lga'),
        ),
    ]
