# Generated by Django 2.0.7 on 2019-02-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0021_auto_20190219_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='payout',
            field=models.FloatField(default=1.0),
        ),
    ]
