# Generated by Django 2.0.7 on 2019-02-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0022_job_payout'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
