# Generated by Django 2.0.7 on 2019-03-05 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0023_application_applicant_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(blank=True, max_length=100)),
                ('applicant_mail', models.EmailField(blank=True, max_length=254)),
                ('applicant_id', models.PositiveIntegerField()),
                ('author_id', models.PositiveIntegerField(default=1)),
                ('status', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.Job')),
            ],
        ),
    ]
