# Generated by Django 2.0.7 on 2019-03-09 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0025_auto_20190308_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jobs.Job'),
        ),
    ]
