# Generated by Django 2.0.7 on 2019-04-07 03:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0026_auto_20190309_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='job',
            name='height',
        ),
        migrations.RemoveField(
            model_name='job',
            name='jslug',
        ),
        migrations.RemoveField(
            model_name='job',
            name='personal_note',
        ),
        migrations.AddField(
            model_name='job',
            name='requirement',
            field=tinymce.models.HTMLField(default='None'),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_Description',
            field=tinymce.models.HTMLField(),
        ),
    ]
