# Generated by Django 2.0.7 on 2019-04-15 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0027_auto_20190407_0433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='Job_Description',
            new_name='Gig_Description',
        ),
    ]
