# Generated by Django 2.1.5 on 2019-02-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='DatePublished',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='TimePublished',
            field=models.DateTimeField(),
        ),
    ]
