# Generated by Django 2.0.7 on 2019-04-07 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='News_Id',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
