# Generated by Django 2.1.5 on 2019-02-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190212_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='DatePublished',
            field=models.DateField(),
        ),
    ]
