# Generated by Django 2.1.5 on 2019-02-17 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_comment_news_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='News_Id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='news.News'),
        ),
    ]
