# Generated by Django 2.0.7 on 2019-01-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Contact_info', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(upload_to='company/logo')),
                ('Facebook', models.URLField()),
                ('Twitter', models.URLField()),
                ('Instagram', models.URLField()),
            ],
        ),
    ]
