"""
Django settings for Phodel project.

Generated by 'django-admin startproject' using Django 2.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import django_heroku
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '&v)u34iz3!k$tko5g_wo(8_$3ho&6gb_gom(2!hfdi82638c+6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '192.168.137.85',
    '192.168.137.249',
    '127.0.0.1',
    '192.168.43.150',
]
LOGIN_REDIRECT_URL = 'Home:homeView'
LOGOUT_REDIRECT_URL='Home:index'

#E-mail settings
# EMAIL_USE_TLS = True
EMAIL_HOST = 'mail.phodel.com.ng'
EMAIL_HOST_USER = 'temidire@phodel.com.ng'
EMAIL_HOST_PASSWORD = 'ABRAHAM13/0609'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True



# Application definition

INSTALLED_APPS = [
#pre-installed apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

#created apps
    'home',
    'account',
    'Jobs',
    'news',
    'blogs',
    'search',

#downloaded apps

    'import_export',
    'crispy_forms',
    'tinymce',
    # 'django_elasticsearch_dsl',
    # 'haystack',
    'star_ratings',
]
# HAYSTACK_SIGNAL_PROCESSOR = 'haystack.signals.RealtimeSignalProcessor'
# HAYSTACK_CONNECTIONS = {
#               'default': {
#                     'ENGINE': 'haystack.backends.elasticsearch_backend.ElasticsearchSearchEngine',
#                     'URL': 'http://127.0.0.1:9200/',
#                     'INDEX_NAME': 'haystack',
#               },
#     }

CRISPY_TEMPLATE_PACK = 'bootstrap4'




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
ROOT_URLCONF = 'Phodel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Phodel.wsgi.application'

STAR_RATINGS_STAR_HEIGHT=12
# STAR_RATINGS_RATING_MODEL = 'account.Pmodel'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'phodel',
        'USER': 'gr8temi',
        'PASSWORD': 'ABRAHAM13/0609',
        'HOST': 'gr8temi.mysql.pythonanywhere-services.com',
        'PORT': '3306',

    }
}

SITE_ID=1

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

FILE_UPLOAD_HANDLERS = ("django_excel.ExcelMemoryFileUploadHandler",
                        "django_excel.TemporaryExcelFileUploadHandler")

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS=(
    os.path.join(BASE_DIR,'asset'),
)
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
)

AUTH_USER_MODEL = 'account.CustomUser'

# Activate Django-Heroku.
django_heroku.settings(locals())